### ISSUE TITLE
Handling of multiline regexes with comments broke from 2.2.0.3 to 2.2.0.4

### ISSUE THREAD

**Issue by sds** [whitequark/parser#190]
The following runs without problem on `parser` 2.2.0.3, but fails on 2.2.0.4. The trigger appears to be the presence of a parenthesis in a comment.

```ruby
require 'astrolabe/builder'
require 'parser/current'

builder = Astrolabe::Builder.new
parser = Parser::CurrentRuby.new(builder)
buffer = Parser::Source::Buffer.new('buffer_name', 1)
buffer.source = <<-CODE
(/
   regex # Some comment containing a )
/x)
CODE

parser.tokenize(buffer)
```

```
~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/parser-2.2.0.4/lib/parser/diagnostic/engine.rb:71:in `process': unmatched close parenthesis: / (Parser::SyntaxError)
   regex # Some comment containing a )
/
        from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/parser-2.2.0.4/lib/parser/builders/default.rb:1434:in `diagnostic'
        from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/parser-2.2.0.4/lib/parser/builders/default.rb:178:in `rescue in regexp_compose'
        from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/parser-2.2.0.4/lib/parser/builders/default.rb:175:in `regexp_compose'
        from ruby21.y:1691:in `_reduce_436'
        from ~/.rbenv/versions/2.1.2/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
        from ~/.rbenv/versions/2.1.2/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
        from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/parser-2.2.0.4/lib/parser/base.rb:175:in `parse'
        from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/parser-2.2.0.4/lib/parser/base.rb:193:in `parse_with_comments'
        from ~/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/parser-2.2.0.4/lib/parser/base.rb:214:in `tokenize'
        from test.rb:13:in `<main>'
```

**Comment by whitequark** [comment]
The reason for this is c2a5e1b1. It... looks like the regexp is invalid? I'm not sure.

**Comment by bbatsov** [comment]
This has also caused problems in RuboCop - see https://github.com/bbatsov/rubocop/pull/1795#issuecomment-93797061

**Comment by whitequark** [comment]
Oh. I think I'm not passing the modifiers to it, so it bails without `//x`.
