### ISSUE TITLE
parser blows up on syntax error

### ISSUE THREAD

**Issue by troessner** [whitequark/parser#273]
```
 ( $ ) ruby-parse -v
ruby-parse based on parser version 2.3.0.5
```

```
  ( $ ) cat bad_syntax.rb
class Create
  def self.

  end
end
```

```
  ( $ ) ruby-parse bad_syntax.rb
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.4-compliant syntax, but you are running 2.2.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Failed on: bad_syntax.rb
/Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic.rb:121:in `[]=': 1...1 out of range (RangeError)
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic.rb:121:in `render_line'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic.rb:96:in `render'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner.rb:147:in `block in prepare_parser'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic/engine.rb:67:in `call'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/diagnostic/engine.rb:67:in `process'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/base.rb:251:in `on_error'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/base.rb:162:in `parse'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner/ruby_parse.rb:132:in `process'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner.rb:202:in `process_buffer'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner.rb:195:in `block in process_files'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner.rb:181:in `each'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner.rb:181:in `process_files'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner.rb:159:in `block in process_all_input'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner.rb:157:in `process_all_input'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner/ruby_parse.rb:128:in `process_all_input'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner.rb:33:in `execute'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/lib/parser/runner.rb:11:in `go'
	from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/parser-2.3.0.5/bin/ruby-parse:6:in `<top (required)>'
	from /Users/timo/.rbenv/versions/2.2.3/bin/ruby-parse:23:in `load'
	from /Users/timo/.rbenv/versions/2.2.3/bin/ruby-parse:23:in `<main>'
```

It seems this error was introduced in parser 2.3. 
Using parser 2.2 the same code does not blow up in your face:

```
  ( $ ) ruby-parse -V
ruby-parse based on parser version 2.2.0
```

```
  ( $ ) ruby-parse bad_syntax.rb
warning: you are loading parser/ruby22 from /Users/timo/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'.
warning: Ruby 2.2 is not released yet and parser support may be incomplete.
bad_syntax.rb:6:1: error: unexpected token $end
```

Another problem we have with this is that parser throws a RangeError in this case where I rather would have expected Parser::SyntaxError which we rescue [here](https://github.com/troessner/reek/blob/master/lib/reek/source/source_code.rb#L84) for instance.

**Comment by whitequark** [comment]
Yep, that's a bug. I'll look into it a bit later.

**Comment by whitequark** [comment]
Bisected to b5b54cfac7.

**Comment by troessner** [comment]
Fast fix!
Could you also please release a 2.3.0.6?

**Comment by whitequark** [comment]
Done

**Comment by troessner** [comment]
Thanks for the super-speedy fix and release!

**Comment by dkogias** [comment]
Another variant of this still here with 2.3.0.6:
```
$ ruby-parse -V
ruby-parse based on parser version 2.3.0.6
$ cat syntax_error.rb 
{
  foo: ->() # I forgot my brace
  }
}
$ ruby -v syntax_error.rb 
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
syntax_error.rb:2: syntax error, unexpected '\n', expecting keyword_do_LAMBDA or tLAMBEG
$ ruby-parse syntax_error.rb 
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.4-compliant syntax, but you are running 2.2.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Failed on: syntax_error.rb
/home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/source/range.rb:112:in `column_range': #<Parser::Source::Range syntax_error.rb 33...34> spans more than one line (RangeError)
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/diagnostic.rb:121:in `render_line'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/diagnostic.rb:94:in `render'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner.rb:147:in `block in prepare_parser'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/diagnostic/engine.rb:67:in `call'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/diagnostic/engine.rb:67:in `process'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/base.rb:251:in `on_error'
	from /home/d/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
	from /home/d/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/base.rb:162:in `parse'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner/ruby_parse.rb:132:in `process'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner.rb:202:in `process_buffer'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner.rb:195:in `block in process_files'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner.rb:181:in `each'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner.rb:181:in `process_files'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner.rb:159:in `block in process_all_input'
	from /home/d/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner.rb:157:in `process_all_input'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner/ruby_parse.rb:128:in `process_all_input'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner.rb:33:in `execute'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/lib/parser/runner.rb:11:in `go'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/parser-2.3.0.6/bin/ruby-parse:6:in `<top (required)>'
	from /home/d/.rvm/gems/ruby-2.2.1/bin/ruby-parse:23:in `load'
	from /home/d/.rvm/gems/ruby-2.2.1/bin/ruby-parse:23:in `<main>'

**Comment by alexdowad** [comment]
@dkoglas I was a bit surprised to see this, because I thought I had that already sorted out in 29a323d. Now I have discovered I made a 1-character mistake in that commit. Opening a PR to fix it now...

**Comment by whitequark** [comment]
@dkogias Fixed.

**Comment by dkogias** [comment]
Thanks for the quick response!

Something I'm missing re: versions/dependencies though?  If I point my Gemfile to either the latest in this repo:

`gem 'parser', github: 'whitequark/parser'`

or the v2.3.0.6 tag:

`gem 'parser', github: 'whitequark/parser', tag: 'v2.3.0.6'`

Rails failes to load with:

```
/home/d/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- parser/lexer (LoadError)
	from /home/d/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/d/.rvm/gems/ruby-2.2.1/bundler/gems/parser-c53da180955e/lib/parser.rb:60:in `<module:Parser>'
	from /home/d/.rvm/gems/ruby-2.2.1/bundler/gems/parser-c53da180955e/lib/parser.rb:17:in `<top (required)>'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /home/d/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
```

whereas if I point to rubygems:

`gem 'parser', '2.3.0.6'`

Rails loads.

**Comment by whitequark** [comment]
Yes, using the repo directly via bundler is not supported with Parser.

**Comment by dkogias** [comment]
I see, thanks.  I'll be watching for a release then!
