### ISSUE TITLE
Parse failure when calling method on a new line

### ISSUE THREAD

**Issue by chrismwendt** [whitequark/parser#297]
Repro:

```ruby
puts(0
    .to_s)
```

```
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.8-compliant syntax, but you are running 2.1.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
(string):3:5: error: unexpected token tDOT
(string):3:     .to_s)
(string):3:     ^     
/var/lib/gems/2.1.0/gems/parser-2.3.1.2/lib/parser/diagnostic/engine.rb:71:in `process': unexpected token tDOT (Parser::SyntaxError)
        from /var/lib/gems/2.1.0/gems/parser-2.3.1.2/lib/parser/base.rb:263:in `on_error'
        from /usr/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
        from /usr/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
        from /var/lib/gems/2.1.0/gems/parser-2.3.1.2/lib/parser/base.rb:162:in `parse'
        from /var/lib/gems/2.1.0/gems/parser-2.3.1.2/lib/parser/base.rb:31:in `parse'
        from parse.rb:13:in `<main>'
```

```
> gem list | ag parser
parser (2.3.1.2)
```

**Comment by whitequark** [comment]
Hmmm, unable to reproduce:
```
$ ./bin/ruby-parse --23 -e t.rb 
(send
  (send nil :t) :rb)
$ ./bin/ruby-parse --22 -e t.rb 
(send
  (send nil :t) :rb)
$ ./bin/ruby-parse --21 -e t.rb 
(send
  (send nil :t) :rb)
$ ./bin/ruby-parse --20 -e t.rb 
(send
  (send nil :t) :rb)
$ cat t.rb
puts(0
    .to_s)
```

**Comment by whitequark** [comment]
Nevermind the previous comment, I forgot how my own CLI works for a moment

**Comment by whitequark** [comment]
Hm, no, still unable to reproduce...
```
$ ./bin/ruby-parse --23 t.rb
(send nil :puts
  (send
    (int 0) :to_s))
$ ./bin/ruby-parse --22 t.rb
(send nil :puts
  (send
    (int 0) :to_s))
$ ./bin/ruby-parse --21 t.rb
(send nil :puts
  (send
    (int 0) :to_s))
$ ./bin/ruby-parse --20 t.rb
(send nil :puts
  (send
    (int 0) :to_s))
$ cat t.rb 
puts(0
    .to_s)
```

**Comment by whitequark** [comment]
I've also tried 2.1.1, with no result. Please reopen if you have a reliable repro. (Maybe there are some funky whitespace characters in your file? There are none in the code in the github issue, at least.)

**Comment by chrismwendt** [comment]
My apologies! I was reading in the file incorrectly and inserting extra new lines.
