### ISSUE TITLE
Comment accidentally getting interpreted as encoding magic comment.

### ISSUE THREAD

**Issue by JoshCheek** [whitequark/parser#443]
While looking into https://github.com/JoshCheek/seeing_is_believing/issues/126

I realized that the string we were inspecting was an HTTP resposnse, which included the header `Accept-Encoding: gzip, deflate, br`. After inspecting it and displaying it at the end of the first line, it was no longer parseable, because it looked like an invalid pragma to specify the encoding of the file.

```ruby
require 'parser/ruby24'

# Parser correctly ignores the encoding and uses utf-8
Parser::Ruby24.parse(<<-RUBY)
puts 1 # encoding: ascii-8bit
puts __ENCODING__
RUBY
# => s(:begin,
#      s(:send, nil, :puts,
#        s(:int, 1)),
#      s(:send, nil, :puts,
#        s(:const,
#          s(:const, nil, :Encoding), :UTF_8)))


# But, when it's not a valid encoding, it explodes
Parser::Ruby24.parse(<<-RUBY)
puts 1 # => "Host: localhost:3000\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: keep-alive"
puts __ENCODING__
RUBY

# !> (string):2:8: error: unexpected token tLABEL
# !> (string):2: Accept-Encoding: gzip, deflate, br
# !> (string):2:        ^~~~~~~~~                  
```

Another example that would work on, line 2, but would explode on line 1:

```ruby
`curl -sIL google.com | grep Enc` # => "Transfer-Encoding: chunked\r\nVary: Accept-Encoding\r\n"
```

**Comment by whitequark** [comment]
Not a bug. You didn't escape a `\n`:
```
[2] pry(main)> x = <<-RUBY
[2] pry(main)* puts 1 # => "Host: localhost:3000\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: keep-alive"
[2] pry(main)* puts __ENCODING__
[2] pry(main)* RUBY
=> "puts 1 # => \"Host: localhost:3000\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: keep-alive\"\nputs __ENCODING__\n"
[3] pry(main)> puts x
puts 1 # => "Host: localhost:3000
Accept-Encoding: gzip, deflate, br
Connection: keep-alive"
puts __ENCODING__
=> nil
```

**Comment by JoshCheek** [comment]
Not sure what you mean, consider this example which has no newlines in the string:

```ruby
require 'parser/ruby24'
Parser::Ruby24.parse("some_code # and a comment 'Accept-Encoding: gzip' in it")

# ~> ArgumentError
# ~> unknown encoding name - gzip
# ~>
# ~> /Users/xjxc322/.gem/ruby/2.5.0/gems/parser-2.4.0.0/lib/parser/source/buffer.rb:66:in `find'
# ~> /Users/xjxc322/.gem/ruby/2.5.0/gems/parser-2.4.0.0/lib/parser/source/buffer.rb:66:in `recognize_encoding'
# ~> /Users/xjxc322/.gem/ruby/2.5.0/gems/parser-2.4.0.0/lib/parser/source/buffer.rb:89:in `reencode_string'
# ~> /Users/xjxc322/.gem/ruby/2.5.0/gems/parser-2.4.0.0/lib/parser/source/buffer.rb:161:in `source='
# ~> /Users/xjxc322/.gem/ruby/2.5.0/gems/parser-2.4.0.0/lib/parser/base.rb:105:in `setup_source_buffer'
# ~> /Users/xjxc322/.gem/ruby/2.5.0/gems/parser-2.4.0.0/lib/parser/base.rb:30:in `parse'
```

I only included the newlines to illustrate that it's a reasonable situation for my gem.

**Comment by JoshCheek** [comment]
Oh, I see what you mean! Yes, my second example was not what I was trying to illustrate.
