### ISSUE TITLE
cannot load such file -- parser/ruby22 when running parser from master branch

### ISSUE THREAD

**Issue by paneq** [whitequark/parser#446]
I wanted to play with `Parser::TreeRewriter` instead of deprecated `Parser::Rewriter` but a new gem version with it is not yet released (but documentation is updated saying Rewriter is deprecated). So I tried using the version from `master` branch but it fails for me.

```
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.9-compliant syntax, but you are running 2.2.8.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.


/Users/rupert/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/bundler/gems/parser-8a8825521af7/lib/parser/current.rb:38:in `require': cannot load such file -- parser/ruby22 (LoadError)
	from /Users/rupert/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/bundler/gems/parser-8a8825521af7/lib/parser/current.rb:38:in `<module:Parser>'
	from /Users/rupert/.rbenv/versions/2.2.8/lib/ruby/gems/2.2.0/bundler/gems/parser-8a8825521af7/lib/parser/current.rb:3:in `<top (required)>'
	from script/onetime/rewrite_functional_positional.rb:1:in `require'
	from script/onetime/rewrite_functional_positional.rb:1:in `<main>'
```

**Comment by whitequark** [comment]
Running Parser as a git dependency from Bundler is not supported (for good reasons). There is nothing I can do about this; build and install the gem locally from source for now. There should be a new release soon™.

**Comment by paneq** [comment]
Thanks for a super quick answer and a workaround. Have a great day.
