### ISSUE TITLE
--emit-json fails with empty / commented files

### ISSUE THREAD

**Issue by lsenta** [whitequark/parser#515]
Hi there, thanks for maintaining this library,
I just started using Ruby & ruby-parse,
it crashes on empty files or files that contains only comments:

```
› echo "# helloworld" > helloworld.rb && ruby-parse ./helloworld.rb --emit-json
Failed on: ./helloworld.rb
Traceback (most recent call last):
        13: from /usr/local/bin/ruby-parse:23:in `<main>'
        12: from /usr/local/bin/ruby-parse:23:in `load'
        11: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/bin/ruby-parse:7:in `<top (required)>'
        10: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner.rb:13:in `go'
         9: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner.rb:35:in `execute'
         8: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner/ruby_parse.rb:137:in `process_all_input'
         7: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner.rb:174:in `process_all_input'
         6: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
         5: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner.rb:176:in `block in process_all_input'
         4: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner.rb:196:in `process_files'
         3: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner.rb:196:in `each'
         2: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner.rb:207:in `block in process_files'
         1: from /usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner.rb:214:in `process_buffer'
/usr/local/lib/ruby/gems/2.5.0/gems/parser-2.5.1.0/lib/parser/runner/ruby_parse.rb:149:in `process': undefined method `to_sexp_array' for nil:NilClass (NoMethodError)
```

**Comment by whitequark** [comment]
Can you submit a PR?
