### ISSUE TITLE
Support parsing open-ended range [1..]

### ISSUE THREAD

**Issue by olleolleolle** [whitequark/parser#564]
Open-ended range fails.

## Reproduce

Have a file with an open range.

```ruby
p [:a, :b, :c, :d, :e][2..]
```

Use 2.6.2.

```
$ ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
```

Try the program with ruby:

```
$ ruby o.rb
[:c, :d, :e]
```

Run `reek` to inspect this file, and see parser fail on `unexpected token tRBRACK`:

```
$ reek o.rb
    Inspecting 1 file(s):
        !!!
        Source 'o.rb' cannot be processed by Reek due to a syntax error in the source file.

        This is a problem that is outside of Reek's scope and should be fixed by you, the
        user, in order for Reek being able to continue.

        Things you can try:
        - Check the syntax of the problematic file
        - If the file is not in fact a Ruby file, exclude it in your .reek.yml file

        Exception message:

        #<Parser::SyntaxError: unexpected token tRBRACK>

        Original backtrace:

        /Users/olle/.rvm/gems/ruby-2.6.2/gems/parser-2.6.2.0/lib/parser/diagnostic/engine.rb:73:in `process'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/parser-2.6.2.0/lib/parser/base.rb:262:in `on_error'
	/Users/olle/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/racc/parser.rb:259:in `_racc_do_parse_c'
	/Users/olle/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/racc/parser.rb:259:in `do_parse'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/parser-2.6.2.0/lib/parser/base.rb:167:in `parse'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/parser-2.6.2.0/lib/parser/base.rb:184:in `parse_with_comments'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/source/source_code.rb:116:in `parse'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/source/source_code.rb:52:in `syntax_tree'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:116:in `syntax_tree'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:120:in `examine_tree'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:94:in `block in run'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:104:in `wrap_exceptions'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:93:in `run'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:61:in `smells'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/examiner.rb:77:in `smelly?'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/report/progress_formatter.rb:43:in `progress'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/report/text_report.rb:22:in `add_examiner'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/command/report_command.rb:25:in `each'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/command/report_command.rb:17:in `execute'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/lib/reek/cli/application.rb:32:in `execute'
	/Users/olle/.rvm/gems/ruby-2.6.2/gems/reek-5.3.1/bin/reek:12:in `<top (required)>'
	/Users/olle/.rvm/gems/ruby-2.6.2/bin/reek:23:in `load'
	/Users/olle/.rvm/gems/ruby-2.6.2/bin/reek:23:in `<main>'
	/Users/olle/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `eval'
	/Users/olle/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `<main>'

        !!!
.
```

**Comment by iliabylich** [comment]
Must be something in Reek:
```
$ bin/ruby-parse --26 -e 'p [:a, :b, :c, :d, :e][2..]'
(send nil :p
  (index
    (array
      (sym :a)
      (sym :b)
      (sym :c)
      (sym :d)
      (sym :e))
    (irange
      (int 2) nil)))
```

**Comment by olleolleolle** [comment]
@iliabylich Thanks for narrowing the target! I will close this issue.

An Issue like this one has been opened in reek.
