### ISSUE TITLE
RubyParser doesn't work for the code that works in Ruby 2.7.0

### ISSUE THREAD

**Issue by mensfeld** [whitequark/parser#653]
I have a code like that:

```ruby
a a: :r do
  O
    #
    .n.c { |a| a.t { S.h(_1) } }
end
```

that for `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]` works, but when trying to parse it with the parser this is what happens:

```
require 'parser/current'
Parser::CurrentRuby.parse(File.read('test.rb'))

Traceback (most recent call last):
       10: from /2.7.0/bin/irb:23:in `<main>'
        9: from /2.7.0/bin/irb:23:in `load'
        8: from /2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        7: from (irb):5
        6: from /2.7.0/lib/ruby/gems/2.7.0/gems/parser-2.7.0.3/lib/parser/base.rb:33:in `parse'
        5: from /2.7.0/lib/ruby/gems/2.7.0/gems/parser-2.7.0.3/lib/parser/base.rb:189:in `parse'
        4: from (eval):3:in `do_parse'
        3: from (eval):3:in `_racc_do_parse_c'
        2: from /2.7.0/lib/ruby/gems/2.7.0/gems/parser-2.7.0.3/lib/parser/base.rb:284:in `on_error'
        1: from /2.7.0/lib/ruby/gems/2.7.0/gems/parser-2.7.0.3/lib/parser/diagnostic/engine.rb:73:in `process'
Parser::SyntaxError (unexpected token tDOT)
```

this affects for now at least RuboCop (didn't report that there as it's not their issue).

result of running it with `ruby --dump=parsetree`:

```
###########################################################
## Do NOT use this node dump for any purpose other than  ##
## debug and research.  Compatibility is not guaranteed. ##
###########################################################

# @ NODE_SCOPE (line: 1, location: (1,0)-(5,3))
# +- nd_tbl: (empty)
# +- nd_args:
# |   (null node)
# +- nd_body:
#     @ NODE_ITER (line: 1, location: (1,0)-(5,3))*
#     +- nd_iter:
#     |   @ NODE_FCALL (line: 1, location: (1,0)-(1,7))
#     |   +- nd_mid: :a
#     |   +- nd_args:
#     |       @ NODE_LIST (line: 1, location: (1,2)-(1,7))
#     |       +- nd_alen: 1
#     |       +- nd_head:
#     |       |   @ NODE_HASH (line: 1, location: (1,2)-(1,7))
#     |       |   +- nd_brace: 0 (keyword argument)
#     |       |   +- nd_head:
#     |       |       @ NODE_LIST (line: 1, location: (1,2)-(1,7))
#     |       |       +- nd_alen: 2
#     |       |       +- nd_head:
#     |       |       |   @ NODE_LIT (line: 1, location: (1,2)-(1,4))
#     |       |       |   +- nd_lit: :a
#     |       |       +- nd_head:
#     |       |       |   @ NODE_LIT (line: 1, location: (1,5)-(1,7))
#     |       |       |   +- nd_lit: :r
#     |       |       +- nd_next:
#     |       |           (null node)
#     |       +- nd_next:
#     |           (null node)
#     +- nd_body:
#         @ NODE_SCOPE (line: 1, location: (1,8)-(5,3))
#         +- nd_tbl: (empty)
#         +- nd_args:
#         |   (null node)
#         +- nd_body:
#             @ NODE_ITER (line: 4, location: (2,2)-(4,32))*
#             +- nd_iter:
#             |   @ NODE_CALL (line: 4, location: (2,2)-(4,8))
#             |   +- nd_mid: :c
#             |   +- nd_recv:
#             |   |   @ NODE_CALL (line: 4, location: (2,2)-(4,6))
#             |   |   +- nd_mid: :n
#             |   |   +- nd_recv:
#             |   |   |   @ NODE_CONST (line: 2, location: (2,2)-(2,3))
#             |   |   |   +- nd_vid: :O
#             |   |   +- nd_args:
#             |   |       (null node)
#             |   +- nd_args:
#             |       (null node)
#             +- nd_body:
#                 @ NODE_SCOPE (line: 4, location: (4,9)-(4,32))
#                 +- nd_tbl: :a
#                 +- nd_args:
#                 |   @ NODE_ARGS (line: 4, location: (4,12)-(4,13))
#                 |   +- nd_ainfo->pre_args_num: 1
#                 |   +- nd_ainfo->pre_init:
#                 |   |   (null node)
#                 |   +- nd_ainfo->post_args_num: 0
#                 |   +- nd_ainfo->post_init:
#                 |   |   (null node)
#                 |   +- nd_ainfo->first_post_arg: (null)
#                 |   +- nd_ainfo->rest_arg: (null)
#                 |   +- nd_ainfo->block_arg: (null)
#                 |   +- nd_ainfo->opt_args:
#                 |   |   (null node)
#                 |   +- nd_ainfo->kw_args:
#                 |   |   (null node)
#                 |   +- nd_ainfo->kw_rest_arg:
#                 |       (null node)
#                 +- nd_body:
#                     @ NODE_ITER (line: 4, location: (4,15)-(4,30))*
#                     +- nd_iter:
#                     |   @ NODE_CALL (line: 4, location: (4,15)-(4,18))
#                     |   +- nd_mid: :t
#                     |   +- nd_recv:
#                     |   |   @ NODE_DVAR (line: 4, location: (4,15)-(4,16))
#                     |   |   +- nd_vid: :a
#                     |   +- nd_args:
#                     |       (null node)
#                     +- nd_body:
#                         @ NODE_SCOPE (line: 4, location: (4,19)-(4,30))
#                         +- nd_tbl: :_1
#                         +- nd_args:
#                         |   @ NODE_ARGS (line: 0, location: (0,-1)-(0,-1))
#                         |   +- nd_ainfo->pre_args_num: 1
#                         |   +- nd_ainfo->pre_init:
#                         |   |   (null node)
#                         |   +- nd_ainfo->post_args_num: 0
#                         |   +- nd_ainfo->post_init:
#                         |   |   (null node)
#                         |   +- nd_ainfo->first_post_arg: (null)
#                         |   +- nd_ainfo->rest_arg: (null)
#                         |   +- nd_ainfo->block_arg: (null)
#                         |   +- nd_ainfo->opt_args:
#                         |   |   (null node)
#                         |   +- nd_ainfo->kw_args:
#                         |   |   (null node)
#                         |   +- nd_ainfo->kw_rest_arg:
#                         |       (null node)
#                         +- nd_body:
#                             @ NODE_CALL (line: 4, location: (4,21)-(4,28))*
#                             +- nd_mid: :h
#                             +- nd_recv:
#                             |   @ NODE_CONST (line: 4, location: (4,21)-(4,22))
#                             |   +- nd_vid: :S
#                             +- nd_args:
#                                 @ NODE_LIST (line: 4, location: (4,25)-(4,27))
#                                 +- nd_alen: 1
#                                 +- nd_head:
#                                 |   @ NODE_DVAR (line: 4, location: (4,25)-(4,27))
#                                 |   +- nd_vid: :_1
#                                 +- nd_next:
#                                     (null node)
```

**Comment by mbj** [comment]
@mensfeld Can you reduce your input? I suspect it boils down to this part, or less.

```
a a: :r do
  O
    #
    .n.c { |a| a.t { S.h(_1) } }
end
```

**Comment by mensfeld** [comment]
@mbj if I reduce it, it does not represent the fact, that when executed with `ruby test.rb` it works.

**Comment by mbj** [comment]
@mensfeld I does not need to run, it needs to parse. As ruby has no static analysis, all `parser` can do is to make sure it produces an AST, not that this AST can be executed without errors.

99 out of 100 ASTs `parser` (and rubies internal) parser can produce will not run without errors.

You can reduce it against `ruby --dump=parsetree` to avoid showing execution.

**Comment by mensfeld** [comment]
@mbj updated.

**Comment by iliabylich** [comment]
@mensfeld `2.7.0.4` has been released - https://rubygems.org/gems/parser/versions/2.7.0.4, could you check it please?

**Comment by mensfeld** [comment]
@iliabylich sure. It will take rubygems couple minutes to propagate this, but once available in the API, I will run it with the newest rubocop and confirm.

**Comment by mensfeld** [comment]
@iliabylich works. Thank you!
