### ISSUE TITLE
array bounds error when using rubocop with parser 3.1

### ISSUE THREAD

**Issue by UltimateGeek** [whitequark/parser#852]
Using rubocop 1.12.1, and parser 3.1.2.0 it crashes:

```
index 0 outside of array bounds: 0...0
<snip>/ruby/2.4.0/gems/parser-3.1.2.0/lib/parser/source/buffer.rb:265:in `fetch'
<snip>/ruby/2.4.0/gems/parser-3.1.2.0/lib/parser/source/buffer.rb:265:in `source_line'
<snip>/ruby/2.4.0/gems/parser-3.1.2.0/lib/parser/source/range.rb:126:in `source_line'
(erb):246:in `block (2 levels) in binding'
(erb):246:in `block (2 levels) in binding'
(erb):239:in `each'
(erb):239:in `block in binding'
(erb):233:in `each'
(erb):233:in `binding'
/opt/rh/rh-ruby24/root/usr/share/ruby/erb.rb:896:in `eval'
/opt/rh/rh-ruby24/root/usr/share/ruby/erb.rb:896:in `result'
<snip>/ruby/2.4.0/gems/rubocop-1.12.1/lib/rubocop/formatter/html_formatter.rb:64:in `render_html'
<snip>/ruby/2.4.0/gems/rubocop-1.12.1/lib/rubocop/formatter/html_formatter.rb:49:in `finished'
<snip>/ruby/2.4.0/gems/rubocop-1.12.1/lib/rubocop/formatter/formatter_set.rb:34:in `public_send'
```

I locked the version of parser down to 3.0.x, and it no longer crashed.

Task definition in my Rakefile:

```ruby
RuboCop::RakeTask.new do |task|
    task.options = ['--fail-level', 'fatal', '--color', '-E', '--format', 'html', '-o' 'rubocop.html', '--format', 'simple', '--format', 'clang']
end
```

**Comment by iliabylich** [comment]
Could you provide source code that makes it crash? A minimal example if possible. Otherwise it' hard to say what's wrong, the backtrace contains only 3 lines from `parser` that don't do anything suspicious,

**Comment by iliabylich** [comment]
Feel free to reopen if there'a specific code snippet that causes this error.
