### ISSUE TITLE
Undefined method '>' for nil:NilClass

### ISSUE THREAD

**Issue by faraaz-deepsource** [whitequark/parser#872]
I have been getting this exception from the parser, while I am parsing the source code. Unfortunately I am not able to determine on which code this happens because I don't have access to the code that `ProcessedSource#from_file` is running on. However it seems to be related to `numparams`. Could it be similar to #616 or #186?

```
NoMethodError: undefined method `>' for nil:NilClass
  from parser/ruby31.rb:7563:in `block in _reduce_614'
  from parser/ruby31.rb:7561:in `reverse_each'
  from parser/ruby31.rb:7561:in `_reduce_614'
  from (eval):3:in `_racc_do_parse_c'
  from (eval):3:in `do_parse'
  from parser/base.rb:190:in `parse'
  from parser/base.rb:238:in `tokenize'
  from rubocop/ast/processed_source.rb:215:in `tokenize'
  from rubocop/ast/processed_source.rb:210:in `parse'
  from rubocop/ast/processed_source.rb:38:in `initialize'
  from rubocop/ast/processed_source.rb:20:in `new'
  from rubocop/ast/processed_source.rb:20:in `from_file'
  from rubocop/runner.rb:398:in `get_processed_source'
  from rubocop/runner.rb:239:in `do_inspection_loop'
  from rubocop/runner.rb:130:in `block in file_offenses'
  from rubocop/runner.rb:155:in `file_offense_cache'
  from rubocop/runner.rb:129:in `file_offenses'
  from rubocop/runner.rb:67:in `block in warm_cache'
  from parallel.rb:587:in `call_with_index'
  from parallel.rb:557:in `process_incoming_jobs'
  from parallel.rb:537:in `block in worker'
  from parallel.rb:528:in `fork'
  from parallel.rb:528:in `worker'
  from parallel.rb:519:in `block in create_workers'
  from parallel.rb:518:in `each'
  from parallel.rb:518:in `each_with_index'
  from parallel.rb:518:in `create_workers'
  from parallel.rb:457:in `work_in_processes'
  from parallel.rb:294:in `map'
  from parallel.rb:238:in `each'
  from rubocop/runner.rb:67:in `warm_cache'
  from rubocop/runner.rb:46:in `run'
  ... <private code>
```

I have tried running it on different permutations of numparams in procs and lambdas but I'm not able to reproduce it

**Comment by iliabylich** [comment]
What is the version of that `parser` that you use? You backtrace doesn't match `ruby31.rb` in the master branch.

> Could it be similar to https://github.com/whitequark/parser/issues/616 or https://github.com/whitequark/parser/issues/186?

I'm pretty sure it is a similar issue. Once I know what is your version I think it should be easy to find the smallest reproducible example.

**Comment by faraaz-deepsource** [comment]
@iliabylich its v3.0.2

**Comment by faraaz-deepsource** [comment]
Here's the backtrace from cloud console 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/113512303/196165559-7be6e365-4106-4a83-b45e-e1a152bd4b89.png">

**Comment by faraaz-deepsource** [comment]
What about #742 ? That seems to be giving a similar error (I apologize if it's not I'm not too familiar with this codebase) but your change for it was to [check if it's not nil first](https://github.com/whitequark/parser/pull/725/files#diff-82c64c23f5bd4e5afe1bc77d2baf50f7254f5702ae6eb855bdac5c044ad35b04).

Would that work for this issue? Also, I noticed the latest `parser` version has different logic for this condition than 3.0.2, Is it possible this error might go away if I upgrade?

**Comment by iliabylich** [comment]
> What about https://github.com/whitequark/parser/issues/742 ? That seems to be giving a similar error (I apologize if it's not I'm not too familiar with this codebase) but your change for it was to [check if it's not nil first](https://github.com/whitequark/parser/pull/725/files#diff-82c64c23f5bd4e5afe1bc77d2baf50f7254f5702ae6eb855bdac5c044ad35b04).

No, that's a different issue.

> Would that work for this issue?

No, like I mentioned above it's related to two internal stack having a different size. Swallowing an error is not a solution here.

> Also, I noticed the latest parser version [has different logic for this condition](https://github.com/whitequark/parser/blob/master/lib/parser/ruby31.y?rgh-link-date=2022-10-18T09%3A36%3A11Z#L3209) than 3.0.2, Is it possible this error might go away if I upgrade?

Oh, right, I changed max numparam stack to also contain information from the context stack, so I think it should be a bit more reliable on master. You could try it. And just FYI: `parser` always moves forward in terms of versions, and so there will be no `3.0.2.1`, better always stick to the latest version if possible.
